import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.environ["DATABASE_URL"]
APP_ENVIRONMENT: str = os.environ.get("APP_ENVIRONMENT", "PRODUCTION")
KAFKA_BOOTSTRAP_SERVERS: str = os.environ["KAFKA_BOOTSTRAP_SERVERS"]
KAFKA_BORROW_BOOK_TOPIC: str = os.environ["KAFKA_BORROW_BOOK_TOPIC"]
KAFKA_RETURN_BOOK_TOPIC: str = os.environ["KAFKA_RETURN_BOOK_TOPIC"]
KAFKA_REMOVE_BOOK_TOPIC: str = os.environ["KAFKA_REMOVE_BOOK_TOPIC"]
KAFKA_ADD_BOOK_TOPIC: str = os.environ["KAFKA_ADD_BOOK_TOPIC"]
KAFKA_CREATE_USER_TOPIC: str = os.environ["KAFKA_CREATE_USER_TOPIC"]
KAFKA_UPDATE_USER_TOPIC: str = os.environ["KAFKA_UPDATE_USER_TOPIC"]
POLL_ADMIN_INTERVAL_SECS: int = int(os.environ["POLL_ADMIN_INTERVAL_SECS"])
